// export const BACKEND_URL = 'http://localhost:8000'
// export const BACKEND_WS_URL = 'ws://localhost:8000'
export const BACKEND_URL = 'http://127.0.0.1:8000'
export const BACKEND_WS_URL = 'ws://127.0.0.1:8000'
// export const BACKEND_URL = 'https://cub-true-shiner.ngrok-free.app'
// export const BACKEND_URL = 'https://cub-true-shiner.ngrok-free.app'