# Generated by Django 6.0 on 2026-01-13 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ecg_values', models.JSONField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='ecg.recordingsession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'timestamp'], name='ecg_sensorr_session_10ca78_idx')],
            },
        ),
    ]
